import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
// The OpenAPI sidebar slice is generated by `docusaurus-plugin-openapi-docs`into `docs/combine-api/` and won't exist on a fresh checkout
let apiItems: SidebarsConfig[string] = [];
try {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  apiItems = require('./docs/combine-api/sidebar').default;
} catch {
  apiItems = [];
}

// API reference nested underneath it as a sub-category.
const combineAwsItems: SidebarsConfig[string] = [
  { type: 'autogenerated', dirName: 'Combine-AWS' },
];

if (Array.isArray(apiItems) && apiItems.length > 0) {
  combineAwsItems.push({
    type: 'category',
    label: 'Combine API',
    link: {
      type: 'generated-index',
      title: 'Combine API',
      description: 'Reference for the Combine TAP API.',
    },
    items: apiItems,
  });
}

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Combine AWS',
      items: combineAwsItems,
    },
    {
      type: 'category',
      label: 'Combine Azure',
      items: [{ type: 'autogenerated', dirName: 'Combine-Azure' }],
    },
  ],
};

export default sidebars;
